/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.gui;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author Prabhashi
 */
public class PatientInfoPanel extends javax.swing.JPanel {

    final DateFormat dateFormat = new SimpleDateFormat("yyyy/MM/dd");
    private String query;
    private PreparedStatement statement;
    private ResultSet result;

    private Date date;
    private int id;
    private String name;
    private String gender;
    private int age;
    private String phoneNo;
    private String address;
    private String disease;
    private String comments;

    /**
     * Creates new form PatientInfoPanel
     */
    public PatientInfoPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonDiscardEdit = new javax.swing.JButton();
        jButtonSaveAllEdit = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        jFormattedTextFieldAgeEdit = new javax.swing.JFormattedTextField();
        jLabel15 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextAreaAddressEdit = new javax.swing.JTextArea();
        jLabel21 = new javax.swing.JLabel();
        jButton9 = new javax.swing.JButton();
        jTextFieldDiseaseEdit = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jComboBoxGenderEdit = new javax.swing.JComboBox();
        jLabel10 = new javax.swing.JLabel();
        jFormattedTextFieldEditID = new javax.swing.JTextField();
        jFormattedTextFieldRegDateEdit = new javax.swing.JFormattedTextField();
        jLabel13 = new javax.swing.JLabel();
        jButtonEdit = new javax.swing.JButton();
        jButtonSearchPatient = new javax.swing.JButton();
        jFormattedTextFieldPhoneNoEdit = new javax.swing.JFormattedTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTextAreaCommentsEdit = new javax.swing.JTextArea();
        jTextFieldNameEdit = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jComboBoxNameEdit = new javax.swing.JComboBox();
        jButtonCancel = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jFormattedTextFieldPrice = new javax.swing.JFormattedTextField();
        jCheckBoxAvailable = new javax.swing.JCheckBox();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList();
        jComboBox1 = new javax.swing.JComboBox();
        jLabel11 = new javax.swing.JLabel();

        setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Patient Information", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 1, 18))); // NOI18N

        jButtonDiscardEdit.setText("Discard Changes");
        jButtonDiscardEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDiscardEditActionPerformed(evt);
            }
        });

        jButtonSaveAllEdit.setText("Save All Changes");
        jButtonSaveAllEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSaveAllEditActionPerformed(evt);
            }
        });

        jLabel14.setText("Age :");

        jFormattedTextFieldAgeEdit.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        jFormattedTextFieldAgeEdit.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jFormattedTextFieldAgeEdit.setEnabled(false);

        jLabel15.setText("Gender :");

        jTextAreaAddressEdit.setColumns(20);
        jTextAreaAddressEdit.setLineWrap(true);
        jTextAreaAddressEdit.setRows(5);
        jTextAreaAddressEdit.setWrapStyleWord(true);
        jTextAreaAddressEdit.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jTextAreaAddressEdit.setEnabled(false);
        jScrollPane3.setViewportView(jTextAreaAddressEdit);

        jLabel21.setText("Comments :");

        jButton9.setText("Discard All Changes");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        jTextFieldDiseaseEdit.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jTextFieldDiseaseEdit.setEnabled(false);

        jLabel25.setText("Registered Date :");

        jLabel16.setText("Phone No :");

        jComboBoxGenderEdit.setModel(new javax.swing.DefaultComboBoxModel(new String[] { " ", "Male", "Female", "Other" }));
        jComboBoxGenderEdit.setEnabled(false);

        jLabel10.setText("Patient Name :");

        jFormattedTextFieldEditID.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jFormattedTextFieldEditIDKeyReleased(evt);
            }
        });

        jFormattedTextFieldRegDateEdit.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jFormattedTextFieldRegDateEdit.setEnabled(false);
        jFormattedTextFieldRegDateEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFormattedTextFieldRegDateEditActionPerformed(evt);
            }
        });

        jLabel13.setText("Name :");

        jButtonEdit.setText("Edit");
        jButtonEdit.setEnabled(false);
        jButtonEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEditActionPerformed(evt);
            }
        });

        jButtonSearchPatient.setText("Search");
        jButtonSearchPatient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSearchPatientActionPerformed(evt);
            }
        });

        jFormattedTextFieldPhoneNoEdit.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        jFormattedTextFieldPhoneNoEdit.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jFormattedTextFieldPhoneNoEdit.setEnabled(false);

        jLabel6.setText("Patient ID :");

        jLabel17.setText("Address :");

        jTextAreaCommentsEdit.setColumns(20);
        jTextAreaCommentsEdit.setLineWrap(true);
        jTextAreaCommentsEdit.setRows(5);
        jTextAreaCommentsEdit.setWrapStyleWord(true);
        jTextAreaCommentsEdit.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jTextAreaCommentsEdit.setEnabled(false);
        jScrollPane4.setViewportView(jTextAreaCommentsEdit);

        jTextFieldNameEdit.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jTextFieldNameEdit.setEnabled(false);

        jLabel20.setText("Disease :");

        jComboBoxNameEdit.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBoxNameEditItemStateChanged(evt);
            }
        });
        jComboBoxNameEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxNameEditActionPerformed(evt);
            }
        });
        jComboBoxNameEdit.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jComboBoxNameEditKeyReleased(evt);
            }
        });

        jButtonCancel.setText("Cancel");
        jButtonCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Room Information", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP));

        jLabel7.setText("Price (per day) Rs :");

        jFormattedTextFieldPrice.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#,##0.00"))));
        jFormattedTextFieldPrice.setEnabled(false);

        jCheckBoxAvailable.setSelected(true);
        jCheckBoxAvailable.setEnabled(false);

        jLabel1.setText("Room Type :");

        jScrollPane5.setViewportView(jList1);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Normal", "Medium", "VIP" }));

        jLabel11.setText("Available :");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(37, 37, 37)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel7)
                                .addComponent(jLabel11))
                            .addGap(29, 29, 29)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jCheckBoxAvailable)
                                .addComponent(jFormattedTextFieldPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jFormattedTextFieldPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addComponent(jCheckBoxAvailable))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jFormattedTextFieldEditID, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel10)
                        .addGap(18, 18, 18)
                        .addComponent(jComboBoxNameEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36)
                        .addComponent(jButtonSearchPatient))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel25)
                            .addComponent(jLabel13)
                            .addComponent(jLabel14)
                            .addComponent(jLabel15)
                            .addComponent(jLabel16)
                            .addComponent(jLabel17)
                            .addComponent(jLabel20)
                            .addComponent(jLabel21))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 222, Short.MAX_VALUE)
                            .addComponent(jFormattedTextFieldPhoneNoEdit)
                            .addComponent(jComboBoxGenderEdit, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jFormattedTextFieldAgeEdit)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jButtonEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButtonDiscardEdit)
                                .addGap(8, 8, 8))
                            .addComponent(jScrollPane4)
                            .addComponent(jFormattedTextFieldRegDateEdit)
                            .addComponent(jTextFieldNameEdit)
                            .addComponent(jTextFieldDiseaseEdit))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(33, 33, 33)
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonSaveAllEdit)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonCancel)))))
                .addContainerGap(68, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jFormattedTextFieldEditID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(jComboBoxNameEdit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonSearchPatient))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel25)
                            .addComponent(jFormattedTextFieldRegDateEdit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(jTextFieldNameEdit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14)
                            .addComponent(jFormattedTextFieldAgeEdit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel15)
                            .addComponent(jComboBoxGenderEdit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel16)
                            .addComponent(jFormattedTextFieldPhoneNoEdit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel17)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldDiseaseEdit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel20))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel21)))
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonEdit)
                    .addComponent(jButtonDiscardEdit)
                    .addComponent(jButtonSaveAllEdit)
                    .addComponent(jButton9)
                    .addComponent(jButtonCancel))
                .addContainerGap(82, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jFormattedTextFieldEditIDKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jFormattedTextFieldEditIDKeyReleased
        String val = jFormattedTextFieldEditID.getText();

//        TODO Fix bug: reset is done even if an arrow key is pressed
        resetFormEdit();

        setFieldsEnabled(false);

        jButtonEdit.setEnabled(false);

        if (isPositiveInteger(val)) {
            id = Integer.parseInt(jFormattedTextFieldEditID.getText());
            try (Connection connection = DriverManager.getConnection("jdbc:mysql://localhost:3306/hospital", "root", null)) {
                query = "select * from patient where id = ?";
                statement = connection.prepareStatement(query);
                statement.setInt(1, id);
                result = statement.executeQuery();

                if (result.next()) {
                    name = result.getString("name");
//                    TODO change name selected
//                    jComboBoxNameEdit.setSelectedItem(name);
                    jComboBoxNameEdit.setSelectedItem(name + " - " + id);

                } else {
                    jComboBoxNameEdit.setSelectedIndex(-1);
                }

            } catch (Exception e) {

            }
        } else {
            jComboBoxNameEdit.setSelectedIndex(-1);
        }
    }//GEN-LAST:event_jFormattedTextFieldEditIDKeyReleased

    private void jFormattedTextFieldRegDateEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFormattedTextFieldRegDateEditActionPerformed

    }//GEN-LAST:event_jFormattedTextFieldRegDateEditActionPerformed

    private void jButtonEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditActionPerformed

        setFieldsEnabled(true);

        //        jComboBoxNameEdit.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "- - Select Name - -", "m 2", "tem 3", "em 4" }));
        jComboBoxGenderEdit.setModel(new javax.swing.DefaultComboBoxModel(new String[]{"Male", "Female", "Other"}));
    }//GEN-LAST:event_jButtonEditActionPerformed

    private void jButtonSearchPatientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSearchPatientActionPerformed
        if (jFormattedTextFieldEditID.getText().equals("")) {
            if (jComboBoxNameEdit.getSelectedIndex() == -1) {
                jButtonEdit.setEnabled(false);
                JOptionPane.showMessageDialog(null, "Enter Patient ID or Name!");
            } else {
                //if Name is selected and id is not selected
                String nameSelected = jComboBoxNameEdit.getSelectedItem().toString();
//                ***************************
                String[] values = nameSelected.split(" - ");
                name = values[0];
                id = Integer.parseInt(values[1]);
                setFieldValues("select * from patient where id = ?", id);
//                try (Connection connection = DriverManager.getConnection("jdbc:mysql://localhost:3306/hospital", "root", null)) {
//                    query = "select * from patient where name = ?";
//                    statement = connection.prepareStatement(query);
//                    statement.setString(1, nameSelected);
//                    result = statement.executeQuery();
//
//                    if (result.next()) {
//
//                        date = result.getDate("register_date");
//
//                        id = result.getInt("id");
//                        //                        String name = result.getString("name");
//                        gender = result.getString("gender");
//                        age = result.getInt("age");
//                        phoneNo = result.getString("phone_no");
//                        address = result.getString("address");
//                        disease = result.getString("disease");
//                        comments = result.getString("comments");
//
//                        jFormattedTextFieldEditID.setText(Integer.toString(id));
//                        jFormattedTextFieldRegDateEdit.setText(dateFormat.format(date));
//                        jTextFieldNameEdit.setText(nameSelected);
//                        jFormattedTextFieldAgeEdit.setText(Integer.toString(age));
//                        jComboBoxGenderEdit.setSelectedItem(gender);
//                        jFormattedTextFieldPhoneNoEdit.setText(phoneNo);
//                        jTextAreaAddressEdit.setText(address);
//                        jTextFieldDiseaseEdit.setText(disease);
//                        jTextAreaCommentsEdit.setText(comments);
//
//                        jButtonEdit.setEnabled(true);

//                    } else {
//                        jButtonEdit.setEnabled(false);
//                        JOptionPane.showMessageDialog(null, "Invalid Patient Name !");
//                    }
//
//                } catch (Exception e) {
//                    System.out.println(e);
//                }
            }
        } else {
            //if id is selected
            id = Integer.parseInt(jFormattedTextFieldEditID.getText());
            setFieldValues("select * from patient where id = ?", id);

//            try (Connection connection = DriverManager.getConnection("jdbc:mysql://localhost:3306/hospital", "root", null)) {
//                query = "select * from patient where id = ?";
//                statement = connection.prepareStatement(query);
//                statement.setInt(1, id);
//                result = statement.executeQuery();
//
//                if (result.next()) {
//
//                    date = result.getDate("register_date");
//
//                    name = result.getString("name");
//                    gender = result.getString("gender");
//                    age = result.getInt("age");
//                    phoneNo = result.getString("phone_no");
//                    address = result.getString("address");
//                    disease = result.getString("disease");
//                    comments = result.getString("comments");
//
//                    jFormattedTextFieldRegDateEdit.setText(dateFormat.format(date));
//                    jTextFieldNameEdit.setText(name);
//                    jFormattedTextFieldAgeEdit.setText(Integer.toString(age));
//                    jComboBoxGenderEdit.setSelectedItem(gender);
//                    jFormattedTextFieldPhoneNoEdit.setText(phoneNo);
//                    jTextAreaAddressEdit.setText(address);
//                    jTextFieldDiseaseEdit.setText(disease);
//                    jTextAreaCommentsEdit.setText(comments);
//                    jComboBoxNameEdit.setSelectedItem(name);
//
//                    jButtonEdit.setEnabled(true);
//
//                } else {
//                    jButtonEdit.setEnabled(false);
//                    JOptionPane.showMessageDialog(null, "Invalid Patient ID !");
//                }
//
//            } catch (Exception e) {
//                System.out.println(e);
//            }
        }
    }//GEN-LAST:event_jButtonSearchPatientActionPerformed

    private void jComboBoxNameEditItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBoxNameEditItemStateChanged
        resetFormEdit();
        setFieldsEnabled(false);
        jButtonEdit.setEnabled(false);
    }//GEN-LAST:event_jComboBoxNameEditItemStateChanged

    private void jComboBoxNameEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxNameEditActionPerformed
       
        if (jComboBoxNameEdit.getSelectedIndex() != -1) {
            String nameSelected = jComboBoxNameEdit.getSelectedItem().toString();
//            ******************************************
            String[] values = nameSelected.split(" - ");
            name = values[0];
            String id = values[1];
//             id = Integer.parseInt(values[1]);
//                setFieldValues("select * from patient where id = ?", id);
            //        System.out.println(nameSelected);
//            try (Connection connection = DriverManager.getConnection("jdbc:mysql://localhost:3306/hospital", "root", null)) {
//                query = "select * from patient where name = ?";
//                statement = connection.prepareStatement(query);
//                statement.setString(1, nameSelected);
//                result = statement.executeQuery();

//                if (result.next()) {
//                    id = result.getInt("id");
            jFormattedTextFieldEditID.setText(id);

//                } else {
//                    jFormattedTextFieldEditID.setText("");
//                }
//            } catch (Exception e) {
//                System.out.println(e);
//            }
        }
    }//GEN-LAST:event_jComboBoxNameEditActionPerformed

    private void jComboBoxNameEditKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jComboBoxNameEditKeyReleased

    }//GEN-LAST:event_jComboBoxNameEditKeyReleased

    private void jButtonDiscardEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDiscardEditActionPerformed
        id = Integer.parseInt(jFormattedTextFieldEditID.getText());
        setFieldValues("select * from patient where id = ?", id);
    }//GEN-LAST:event_jButtonDiscardEditActionPerformed

    private void jButtonSaveAllEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSaveAllEditActionPerformed
        patientEdit();
    }//GEN-LAST:event_jButtonSaveAllEditActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        id = Integer.parseInt(jFormattedTextFieldEditID.getText());
        setFieldValues("select * from patient where id = ?", id);
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButtonCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelActionPerformed
        resetFormEdit();
        MainInterface.setDefaultLayout();
    }//GEN-LAST:event_jButtonCancelActionPerformed

    public void patientEdit() {
        id = Integer.parseInt(jFormattedTextFieldEditID.getText());

        if (jTextFieldNameEdit.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Please enter the name!");
        } else if (jFormattedTextFieldAgeEdit.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Please enter the age!");
        } else {
            try (
                    Connection connection = DriverManager.getConnection("jdbc:mysql://localhost:3306/hospital", "root", null)) {

                query = "Update Patient set name=?, gender=?, age=?, phone_no=?, address=?, disease=?, comments=? where id=? ";
                statement = connection.prepareStatement(query);

                statement.setString(1, jTextFieldNameEdit.getText());

                gender = jComboBoxGenderEdit.getSelectedItem().toString();
                statement.setString(2, gender);

                statement.setString(3, jFormattedTextFieldAgeEdit.getText());
                statement.setString(4, jFormattedTextFieldPhoneNoEdit.getText());
                statement.setString(5, jTextAreaAddressEdit.getText());
                statement.setString(6, jTextFieldDiseaseEdit.getText());
                statement.setString(7, jTextAreaCommentsEdit.getText());
                statement.setInt(8, id);

                statement.executeUpdate();

                JOptionPane.showMessageDialog(null, "Changes were successfully added !");
                resetFormEdit();
                MainInterface.setDefaultLayout();

            } catch (Exception e) {
                System.out.println(e);
            }
        }
    }

    private void setFieldValues(String query, Object val) {
        try (Connection connection = DriverManager.getConnection("jdbc:mysql://localhost:3306/hospital", "root", null)) {

            statement = connection.prepareStatement(query);
            if (val instanceof Integer) {
                int i;
                i = (int) val;
                statement.setInt(1, i);
            } else if (val instanceof String) {
                String str = (String) val;
                statement.setString(1, str);
            }

            result = statement.executeQuery();

            if (result.next()) {

                date = result.getDate("register_date");
                id = result.getInt("id");
                name = result.getString("name");
                gender = result.getString("gender");
                age = result.getInt("age");
                phoneNo = result.getString("phone_no");
                address = result.getString("address");
                disease = result.getString("disease");
                comments = result.getString("comments");

                jFormattedTextFieldEditID.setText(Integer.toString(id));
                jFormattedTextFieldRegDateEdit.setText(dateFormat.format(date));
                jTextFieldNameEdit.setText(name);
                jFormattedTextFieldAgeEdit.setText(Integer.toString(age));
                jComboBoxGenderEdit.setSelectedItem(gender);
                jFormattedTextFieldPhoneNoEdit.setText(phoneNo);
                jTextAreaAddressEdit.setText(address);
                jTextFieldDiseaseEdit.setText(disease);
                jTextAreaCommentsEdit.setText(comments);
//              TODO Change the selected item name
//                jComboBoxNameEdit.setSelectedItem(name);
                jComboBoxNameEdit.setSelectedItem(name + " - " + id);

                jButtonEdit.setEnabled(true);

            } else {
                jButtonEdit.setEnabled(false);
                if (val instanceof Integer) {
                    JOptionPane.showMessageDialog(null, "Invalid Patient ID !");

                } else if (val instanceof String) {
                    JOptionPane.showMessageDialog(null, "Invalid Patient Name !");

                }
            }

        } catch (Exception e) {
            System.out.println(e);
        }
    }

    public void resetFormEdit() {
        jFormattedTextFieldRegDateEdit.setText("");
        jTextFieldNameEdit.setText("");
        jFormattedTextFieldAgeEdit.setText("");
        jComboBoxGenderEdit.setSelectedIndex(0);
        jFormattedTextFieldPhoneNoEdit.setText("");
        jTextAreaAddressEdit.setText("");
        jTextFieldDiseaseEdit.setText("");
        jTextAreaCommentsEdit.setText("");
//        jComboBoxNameEdit.setSelectedItem(name);
    }

    private boolean isPositiveInteger(String str) {
        if (str.equals("")) {
            return false;
        }
        char c;
        for (int i = 0; i < str.length(); i++) {
            c = str.charAt(i);
            if (c > '9' || c < '0') {
                return false;
            }
        }
        return true;
    }

    private void setFieldsEnabled(boolean isEnabled) {
        jTextFieldNameEdit.setEnabled(isEnabled);
        jFormattedTextFieldAgeEdit.setEnabled(isEnabled);
        jComboBoxGenderEdit.setEnabled(isEnabled);
        jFormattedTextFieldPhoneNoEdit.setEnabled(isEnabled);
        jTextAreaAddressEdit.setEnabled(isEnabled);
        jTextFieldDiseaseEdit.setEnabled(isEnabled);
        jTextAreaCommentsEdit.setEnabled(isEnabled);
    }

    public void setJComboBoxNameEdit(String[] names) {
        jComboBoxNameEdit.setModel(new javax.swing.DefaultComboBoxModel(names));
//        jComboBoxNameEdit.setSelectedIndex(-1);
    }

    public void setJFormattedTextFieldEditID(String text) {
        jFormattedTextFieldEditID.setText(text);
    }

    public void setJComboBoxNameEditIndex(int index) {
        jComboBoxNameEdit.setSelectedIndex(index);
    }

    public void setJButtonEditEnable(boolean isEnabled) {
        jButtonEdit.setEnabled(isEnabled);
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton9;
    private javax.swing.JButton jButtonCancel;
    private javax.swing.JButton jButtonDiscardEdit;
    private javax.swing.JButton jButtonEdit;
    private javax.swing.JButton jButtonSaveAllEdit;
    private javax.swing.JButton jButtonSearchPatient;
    private javax.swing.JCheckBox jCheckBoxAvailable;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JComboBox jComboBoxGenderEdit;
    private javax.swing.JComboBox jComboBoxNameEdit;
    private javax.swing.JFormattedTextField jFormattedTextFieldAgeEdit;
    private javax.swing.JTextField jFormattedTextFieldEditID;
    private javax.swing.JFormattedTextField jFormattedTextFieldPhoneNoEdit;
    private javax.swing.JFormattedTextField jFormattedTextFieldPrice;
    private javax.swing.JFormattedTextField jFormattedTextFieldRegDateEdit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JList jList1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTextArea jTextAreaAddressEdit;
    private javax.swing.JTextArea jTextAreaCommentsEdit;
    private javax.swing.JTextField jTextFieldDiseaseEdit;
    private javax.swing.JTextField jTextFieldNameEdit;
    // End of variables declaration//GEN-END:variables
}
